# Configurações do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ipem_db?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=api_user
spring.datasource.password=SENHA123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desativa recursos que podem causar conflito na primeira execução
spring.flyway.enabled=false
spring.h2.console.enabled=false

# Segurança JWT (Evita o erro de inicialização do TokenService)
api.security.token.secret=${JWT_SECRET:3f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0}